trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    displayName: Install Node.js
    inputs:
      versionSpec: '20.x'

  - task: Bash@3
    displayName: Install allurectl
    inputs:
      targetType: inline
      script: |
        # wget https://github.com/allure-framework/allurectl/releases/latest/download/allurectl_linux_amd64 -O ./allurectl
        wget https://github.com/allure-framework/allurectl/releases/download/2.15.1/allurectl_linux_amd64 -O ./allurectl
        chmod +x ./allurectl

  - script: |
      npm install
      ./allurectl watch -- ./gradlew clean test
      printenv | grep "ALLURE_" || true
      printenv | grep "TEST_" || true
      printenv | grep "AZURE_" || true
      echo "All variables"
      printenv
    displayName: npm install and build
    env:
      ALLURE_ENDPOINT: https://testing.qatools.cloud/
      ALLURE_PROJECT_ID: '1201'
      ALLURE_TOKEN: $(ALLURE_TOKEN)
      ALLURE_RESULTS: build/allure-results
      ALLURE_LAUNCH_NAME: $(Build.DefinitionName)-$(Build.BuildNumber)
      TEST_BRANCH: $(Build.SourceBranchName)
      ALLURE_LAUNCH_TAGS: $(Build.SourceBranchName), azure
      AZURE_BROWSER: $(AZURE_BROWSER)
      AZURE_HOST: $(AZURE_HOST)

  - publish: $(System.DefaultWorkingDirectory)/build/allure-results
    artifact: allure-results
    displayName: Publish Allure results
    condition: succeededOrFailed()